name: Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.7.x', '2.6.x', '2.5.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install

    - name: Run test
      run: bundle exec rspec spec
